# Generated by Django 3.2.19 on 2023-05-22 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmshop', '0002_auto_20230517_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Lamb', 'Lamb'), ('Chicken', 'Chicken')], default='Beef', max_length=100),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('product_id', models.ManyToManyField(related_name='product_id', to='farmshop.Product')),
                ('user_id', models.ManyToManyField(related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
