# Generated by Django 3.2.19 on 2023-05-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0007_auto_20230529_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritem',
            old_name='product',
            new_name='products',
        ),
    ]
