# Generated by Django 3.2.19 on 2023-05-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0011_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(blank=True, default=1,
                                    on_delete=django.db.models.deletion.CASCADE,  # noqa
                                    to='farmshop.orderitem'),
            preserve_default=False,
        ),
    ]
