# Generated by Django 3.2.19 on 2023-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0012_auto_20230530_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='farmshop.OrderItem'),
        ),
    ]
